<?php
session_start();
if(!isset($_SESSION['userid'])) {
    //die('Please <a href="login.php">login</a> first!');
    echo "Please <a href='login.php'>login</a> first!";
    echo "<br/><br/>";
    echo "<img src='img/loading.gif' />";
    header( "refresh:8;url=login.php" );
    die('');
}
require 'api/db_config.php';

if (isset($_GET["idProject"])) { $idProject  = $_GET["idProject"]; } else { $idProject=0; };
if (isset($_GET["idApplication"])) { $idApplication  = $_GET["idApplication"]; } else { $idApplication=0; };
$project_name = "";
$application_name = "";
$application_desc = "";

if (isset($_GET["add_component_1"])) { addComp($mysqli, $idApplication, 1); };
if (isset($_GET["act_component_1"])) { actComp($mysqli, $idApplication, 1); };
if (isset($_GET["deact_component_1"])) { deactComp($mysqli, $idApplication, 1); };
if (isset($_GET["del_component_1"])) { delComp($mysqli, $idApplication, 1); };
if (isset($_GET["add_component_2"])) { addComp($mysqli, $idApplication, 2); };
if (isset($_GET["act_component_2"])) { actComp($mysqli, $idApplication, 2); };
if (isset($_GET["deact_component_2"])) { deactComp($mysqli, $idApplication, 2); };
if (isset($_GET["del_component_2"])) { delComp($mysqli, $idApplication, 2); };
if (isset($_GET["add_component_3"])) { addComp($mysqli, $idApplication, 3); };
if (isset($_GET["act_component_3"])) { actComp($mysqli, $idApplication, 3); };
if (isset($_GET["deact_component_3"])) { deactComp($mysqli, $idApplication, 3); };
if (isset($_GET["del_component_3"])) { delComp($mysqli, $idApplication, 3); };
if (isset($_GET["add_component_4"])) { addComp($mysqli, $idApplication, 4); };
if (isset($_GET["act_component_4"])) { actComp($mysqli, $idApplication, 4); };
if (isset($_GET["deact_component_4"])) { deactComp($mysqli, $idApplication, 4); };
if (isset($_GET["del_component_4"])) { delComp($mysqli, $idApplication, 4); };
if (isset($_GET["add_component_5"])) { addComp($mysqli, $idApplication, 5); };
if (isset($_GET["act_component_5"])) { actComp($mysqli, $idApplication, 5); };
if (isset($_GET["deact_component_5"])) { deactComp($mysqli, $idApplication, 5); };
if (isset($_GET["del_component_5"])) { delComp($mysqli, $idApplication, 5); };
if (isset($_GET["add_component_6"])) { addComp($mysqli, $idApplication, 6); };
if (isset($_GET["act_component_6"])) { actComp($mysqli, $idApplication, 6); };
if (isset($_GET["deact_component_6"])) { deactComp($mysqli, $idApplication, 6); };
if (isset($_GET["del_component_6"])) { delComp($mysqli, $idApplication, 6); };
if (isset($_GET["add_component_7"])) { addComp($mysqli, $idApplication, 7); };
if (isset($_GET["act_component_7"])) { actComp($mysqli, $idApplication, 7); };
if (isset($_GET["deact_component_7"])) { deactComp($mysqli, $idApplication, 7); };
if (isset($_GET["del_component_7"])) { delComp($mysqli, $idApplication, 7); };

$sql = "SELECT * FROM `project` WHERE `id` = ".$idProject;

$result = $mysqli->query($sql);

$num_rows = mysqli_num_rows($result);

if ($result->num_rows > 0) {
    // output data of each row
    while($row = $result->fetch_assoc()) {
        // echo "id: " . $row["id"]. " - Name: " . $row["name"]. "  - Description: " . $row["desc"]. "<br/>";
        $project_name = $row["name"];
    }
} else {
    //echo "0 results";
}

$sql = "SELECT * FROM `application` WHERE `id`=".$idApplication;

$result = $mysqli->query($sql);

$num_rows = mysqli_num_rows($result);

if ($result->num_rows > 0) {
    // output data of each row
    while($row = $result->fetch_assoc()) {
        // echo "id: " . $row["id"]. " - Name: " . $row["name"]. "  - Description: " . $row["desc"]. "<br/>";
        $application_name = $row["name"];
        $application_desc = $row["desc"];
    }
} else {
    //echo "0 results";
}


//Abfrage der Nutzer ID vom Login
$userid = $_SESSION['userid'];
 
// get user name from database
$sql = "SELECT * FROM `user` WHERE `id` = ".$userid;
$result = $mysqli->query($sql);
$row = $result->fetch_assoc();

$userName = $row["name"];
$userEmail = $row["email"];

function addComp($mysqli, $idApplication, $idComp) {
    // ICD Generator
    $templ_component[1] = '{"LaTeX":{"Enabled":true},"CSV":{"Enabled":true,"Separator":"","Delimiter":""}}';
    // Datapool
    $templ_component[2] = '{"prefix":"","author":"Automatically Generated by CORDET Editor","copyright":"","param_attr":"","var_attr":"","max_line_length":80,"indent":2,"includes":["CrFwUserConstants.h"]}';
    // Specification
    $templ_component[3] = '{}';
    // MIB Generator
    $templ_component[4] = '{"general":{"release":0,"issue":1,"preamble":""},"txf":{"preamble":"","offset":0},"paf":{"preamble":"","offset":0},"pcf":{"preamble":"","offset":0},"pcpc":{"preamble":"","offset":0},"ccf":{"preamble":"","offset":0},"cpc":{"preamble":"","offset":0},"pid":{"preamble":"","offset":0},"prf":{"preamble":"","offset":0}}';
    // Packet access functions
    $templ_component[5] = '{"prefix":"","author":"Automatically Generated by CORDET Editor","copyright":"","max_line_length":80,"indent":2,"struct_attr":"","endian":{"swap":true,"fnc":"__builtin_bswap"},"crc_size":2,"includes":["CrFwUserConstants.h"]}';
    // CordetFw
    $templ_component[6] = '{"prefix":"","author":"Automatically Generated by CORDET Editor","copyright":"","max_line_length":80,"indent":2,"CrFwOutFactoryMaxNOfOutCmp":50,"CrFwInFactoryMaxNOfInCmd":50,"CrFwInFactoryMaxNOfInRep":50,"CrFwOutRegistryN":50,"includes":["CrFwUserConstants.h"]}';
    // Datapool (v2)
    $templ_component[7] = '{"prefix":"","author":"Automatically Generated by CORDET Editor","copyright":"","param_attr":"","var_attr":"","max_line_length":80,"indent":2,"includes":["CrFwUserConstants.h"]}';
    
    $sql = 'INSERT INTO `applicationcomponent` (idApplication, idComponent, setting) VALUES ('.$idApplication.', '.$idComp.', \''.$templ_component[$idComp].'\')';
    //echo "Add component ".$idComp."<br/>";
    //echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$sql."<br/>";
    $result = $mysqli->query($sql);
    //echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result: ".$result."<br/>";
}
function actComp($mysqli, $idApplication, $idComp) {
    $sql = 'UPDATE `applicationcomponent` SET `active` = 1 WHERE `idApplication` = '.$idApplication.' AND `idComponent` = '.$idComp;
    $result = $mysqli->query($sql);
}
function deactComp($mysqli, $idApplication, $idComp) {
    $sql = 'UPDATE `applicationcomponent` SET `active` = 0 WHERE `idApplication` = '.$idApplication.' AND `idComponent` = '.$idComp;
    $result = $mysqli->query($sql);
}
function delComp($mysqli, $idApplication, $idComp) {
    $sql = 'DELETE FROM `applicationcomponent` WHERE idApplication = '.$idApplication.' AND idComponent = '.$idComp;
    //echo "Delete component ".$idComp."<br/>";
    //echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$sql."<br/>";
    $result = $mysqli->query($sql);
    //echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result: ".$result."<br/>";
}
?>
<!DOCTYPE html>
<html>
<head>
	<title>Application - Components</title>
	<!-- https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css -->
	<link rel="stylesheet" type="text/css" href="ext/bootstrap/3.3.7/css/bootstrap.min.css">
	<!-- https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.js -->
	<script type="text/javascript" src="ext/ajax/libs/jquery/3.1.0/jquery.js"></script>
	<!-- https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js -->
	<script type="text/javascript" src="ext/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
	<!-- https://cdnjs.cloudflare.com/ajax/libs/twbs-pagination/1.3.1/jquery.twbsPagination.min.js -->
	<script type="text/javascript" src="ext/ajax/libs/twbs-pagination/1.3.1/jquery.twbsPagination.min.js"></script>
	<!-- https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js -->
	<script src="ext/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js"></script>
	<!-- //cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js -->
	<script type="text/javascript" src="ext/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<!-- //cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css -->
	<link href="ext/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"> 
	<link rel="stylesheet" type="text/css" href="int/layout.css">
    <script type="text/javascript" src="int/config.js"></script>
	<script type="text/javascript" src="js/item-ajax.js"></script>
	<style type="text/css">

	</style>
</head>
<body>

	<div class="container">

		<div class="row">
		    <div class="col-lg-12 margin-tb">
		        <div class="pull-left">
		            <h2>Project <?php echo $project_name;?> - Application <?php echo $application_name;?> - Components</h2>
		        </div>
				
				<!--
		        <div class="pull-right">
				<button type="button" class="btn btn-success" data-toggle="modal" data-target="#create-item">
					  Create Item
				</button>
		        </div>
				-->
		    </div>
		</div>

<?php

$arr_comp = array();
$act_comp = array();

$sql = "SELECT * FROM `component` AS c, `applicationcomponent` AS ac WHERE c.id = ac.idComponent AND ac.idApplication = ".$idApplication." ORDER BY `idComponent` ASC";

$result = $mysqli->query($sql);

$num_rows = mysqli_num_rows($result);

if ($result->num_rows > 0) {

    // output data of each row
    while($row = $result->fetch_assoc()) {
        $arr_comp[$row["id"]] = $row["name"];
        if (array_key_exists('active', $row)) {
            $act_comp[$row["id"]] = $row["active"];
        } else {
            $act_comp[$row["id"]] = 2;
        }
    }
}


$sql = "SELECT * FROM `component` ORDER BY `id`";

$result = $mysqli->query($sql);

$num_rows = mysqli_num_rows($result);

echo "$num_rows hits<br/><br/>";

echo "<form>";
echo "<input type='hidden' name='idProject' value='".$idProject."' />";
echo "<input type='hidden' name='idApplication' value='".$idApplication."' />";

if ($result->num_rows > 0) {
    // output data of each row
    while($row = $result->fetch_assoc()) {
        // echo "id: " . $row["id"]. " - Name: " . $row["name"]. "  - Description: " . $row["desc"]. "<br/>";
        if (array_key_exists($row["id"], $arr_comp)) {
            echo "<div style='height:30px; padding:5px; width:50%; background-color:lightblue;'>";
            echo "<a href='open_component_editor.php?id=".$row["id"]."&idProject=".$idProject."&idApplication=".$idApplication."'>".$row["id"]." <b>".$arr_comp[$row["id"]]."</b></a>";
            //echo "<span style='float:right;'>[DEL]&nbsp;</span>";
            if ($act_comp[$row["id"]]==1) {
                echo "<button style='float:right;height:20px;display:flex;justify-content:center;align-items:center;' type='submit' class='btn btn-warning deactivate-item' name='deact_component_".$row["id"]."'>DEACT</button>";
            } else if ($act_comp[$row["id"]]==2) {
                echo "<button style='float:right;height:20px;display:flex;justify-content:center;align-items:center;' type='submit' class='btn btn-danger remove-item' name='del_component_".$row["id"]."' onclick='return confirm(\"Are you sure to delete this component?\")'>DEL</button>";
            } else {
                echo "<button style='float:right;height:20px;display:flex;justify-content:center;align-items:center;margin-left:5px;' type='submit' class='btn btn-warning activate-item' name='act_component_".$row["id"]."'>ACT</button>";
                echo "<button style='float:right;height:20px;display:flex;justify-content:center;align-items:center;' type='submit' class='btn btn-danger remove-item' name='del_component_".$row["id"]."' onclick='return confirm(\"Are you sure to delete this component?\")'>DEL</button>";
            }
            echo "</div>";
        } else {
            echo "<div style='height:30px; padding:5px; width:50%; background-color:lightgray;'>";
            //echo "<a href='open_component_editor.php?id=".$row["id"]."' >".$row["id"]." <b>".$row["name"]."</b></a>";
            echo $row["id"]." <b>".$row["name"]."</b>";
            //echo "<span style='float:right;'>[ADD]&nbsp;</span>";
            echo "<button style='float:right;height:20px;display:flex;justify-content:center;align-items:center;' type='submit' class='btn btn-success' name='add_component_".$row["id"]."'>ADD</button>";
            echo "</div>";
        }
        echo "<br/>";
    }
} else {
    echo "0 results";
}

echo "</form>";
?>

<!--<br/>

<h2>Existing Components for this Application</h2>

<?php

$sql = "SELECT * FROM `component` AS c, `applicationcomponent` AS ac WHERE c.id = ac.idComponent AND ac.idApplication = ".$idApplication." ORDER BY `idComponent` ASC";

$result = $mysqli->query($sql);

$num_rows = mysqli_num_rows($result);

echo "$num_rows hits<br/><br/>";

if ($result->num_rows > 0) {
    // output data of each row
    while($row = $result->fetch_assoc()) {
        // echo "id: " . $row["id"]. " - Name: " . $row["name"]. "  - Description: " . $row["desc"]. "<br/>";
        echo "<div style='height:30px; padding:5px; width:50%; background-color:lightblue;'>";
        echo "<a href='open_component_editor.php?id=".$row["id"]."&idProject=".$idProject."&idApplication=".$idApplication."'>".$row["id"]." <b>".$row["name"]."</b></a>&nbsp;&nbsp;&nbsp;".substr($row["setting"],0,50);
        echo "</div>";
        echo "<br/>";
    }
} else {
    echo "0 results";
}

?>
-->

				<div class="topcorner_left">
<?php include 'logos.php'; ?>
					<br/><br/>
					You are logged in as: <br/>
					<?php 
						echo "<b>".$userName."</b><br/>";
					?>
					<br/><br/>
					<a class="a_btn" href="open_application.php?idProject=<?php echo $idProject; ?>&idApplication=<?php echo $idApplication; ?>" target="_self">>> BACK <<</a>
					<br/>
					<a class="a_btn" href="index.php" target="_self">>> HOME <<</a>
				</div>

	</div>
</body>

</html>