-- ALTER TABLE {TABLENAME} 
-- ADD [COLUMN] {COLUMNNAME} {TYPE} {NULL|NOT NULL} 
-- CONSTRAINT {CONSTRAINT_NAME} DEFAULT {DEFAULT_VALUE}
-- WITH VALUES

ALTER TABLE `applicationcomponent`
ADD `active2` TINYINT(4) NOT NULL 
DEFAULT 1 
AFTER `idComponent`;


